FROM amazoncorretto:23

# EXPOSE 1099

WORKDIR /Server

# COPY ServerInterface.java ./
# COPY ServerObject.java ./
# COPY Server.java ./

# COPY ClientInterface.java ./
# COPY ClientObject.java ./

# COPY *.java ./
#COPY ./bin ./
#COPY ./lib ./

COPY ./target/gRPC-1.0-SNAPSHOT-Server.jar ./

CMD ["/bin/bash"]