name: gRPC_chat
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    container_name: server
    ports:
     - "8080:8080"
    stdin_open: true
    tty: true
    command: >
      bash -c "
      ./mvnw exec:java -Dexec.mainClass='wmfx.Server' --quiet
      "
  client1:
    build:
      context: .
      dockerfile: Dockerfile_client
    container_name: client1
    stdin_open: true
    tty: true
    command: >
      bash -c "
      ./client_delay.sh
      "
  client2:
    build:
      context: .
      dockerfile: Dockerfile_client
    container_name: client2
    stdin_open: true
    tty: true
    command: >
      bash -c "
      ./client_delay.sh
      "