name: chatserver
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    container_name: server
    # ports:
    #   - "1099:1099"
    stdin_open: true
    tty: true
    command: > 
      bash -c "
      java -jar gRPC-1.0-SNAPSHOT-Server.jar
      "
  client1:
    build:
      context: .
      dockerfile: Dockerfile_client
    container_name: client1
    depends_on:
      - server
    stdin_open: true
    tty: true
    command: >
      bash -c "
      java -jar gRPC-1.0-SNAPSHOT-Client.jar
      "
  client2:
    build:
      context: .
      dockerfile: Dockerfile_client
    container_name: client2
    depends_on:
      - server
    stdin_open: true
    tty: true
    command: >
      bash -c "
      java -jar gRPC-1.0-SNAPSHOT-Client.jar
      "